-- Create game_questions table
CREATE TABLE IF NOT EXISTS public.game_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_type TEXT NOT NULL CHECK (game_type IN ('consultor', 'termo')),
    content JSONB NOT NULL,
    difficulty TEXT DEFAULT 'easy',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create empire_items table
CREATE TABLE IF NOT EXISTS public.empire_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('active', 'passive')),
    base_cost NUMERIC NOT NULL,
    base_income NUMERIC NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.game_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empire_items ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'game_questions' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON public.game_questions FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'empire_items' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON public.empire_items FOR SELECT USING (true);
    END IF;
END $$;

-- Clean existing data to avoid duplicates if re-running
TRUNCATE TABLE public.game_questions RESTART IDENTITY;
TRUNCATE TABLE public.empire_items RESTART IDENTITY;

-- Seed Data: O Consultor (15 Scenarios)
INSERT INTO public.game_questions (game_type, content, difficulty) VALUES
('consultor', '{"text": "Investimento com retorno garantido de 10% ao mês.", "type": "bad", "explanation": "Golpe! Retornos garantidos muito acima do mercado (como 1% a.m.) geralmente são pirâmides financeiras."}', 'easy'),
('consultor', '{"text": "Empréstimo pessoal com juros de 8% ao mês para comprar roupas.", "type": "bad", "explanation": "Juros abusivos! 8% ao mês vira mais de 150% ao ano. Nunca tome dívida cara para consumo."}', 'easy'),
('consultor', '{"text": "Reserva de Emergência no Tesouro Selic.", "type": "good", "explanation": "Ótima escolha! O Tesouro Selic é seguro e tem liquidez diária, ideal para emergências."}', 'easy'),
('consultor', '{"text": "Vender todas as ações porque o mercado caiu hoje.", "type": "bad", "explanation": "Pânico! Vender na baixa consolida o prejuízo. O ideal é analisar os fundamentos e pensar no longo prazo."}', 'easy'),
('consultor', '{"text": "Aporte mensal em fundos imobiliários para gerar renda passiva.", "type": "good", "explanation": "Excelente estratégia! A constância nos aportes e o reinvestimento dos dividendos criam uma bola de neve."}', 'easy'),
('consultor', '{"text": "Financiar um carro de luxo em 60x sem entrada.", "type": "bad", "explanation": "Cuidado! O custo total será muito maior que o valor do carro, e o veículo desvaloriza rápido."}', 'medium'),
('consultor', '{"text": "Diversificar a carteira entre Renda Fixa e Renda Variável.", "type": "good", "explanation": "Isso reduz riscos! Não colocar todos os ovos na mesma cesta protege seu patrimônio."}', 'medium'),
('consultor', '{"text": "Título de Capitalização oferecido pelo gerente do banco.", "type": "bad", "explanation": "Péssimo negócio! Geralmente rende menos que a poupança e seu dinheiro fica preso. É um jogo, não investimento."}', 'medium'),
('consultor', '{"text": "Seguro de Vida para proteger sua família.", "type": "good", "explanation": "Responsável! Proteção financeira para dependentes é fundamental em um planejamento financeiro sólido."}', 'medium'),
('consultor', '{"text": "Usar a Reserva de Emergência para comprar ações em queda.", "type": "bad", "explanation": "Arriscado! A Reserva de Emergência deve ficar em liquidez imediata e baixo risco, não em renda variável."}', 'medium'),
('consultor', '{"text": "Reinvestir os dividendos recebidos.", "type": "good", "explanation": "O segredo da riqueza! Reinvestir cria o efeito de juros compostos, acelerando o crescimento do patrimônio."}', 'hard'),
('consultor', '{"text": "Comprar imóvel na planta sem verificar a construtora.", "type": "bad", "explanation": "Alto risco! A obra pode atrasar ou a construtora falir. Sempre pesquise o histórico antes."}', 'hard'),
('consultor', '{"text": "Aumentar os aportes mensais ao receber um aumento de salário.", "type": "good", "explanation": "Mentalidade correta! Evite inflar seu custo de vida proporcionalmente. Invista a diferença."}', 'hard'),
('consultor', '{"text": "Pegar empréstimo para investir em criptomoedas.", "type": "bad", "explanation": "Perigo máximo! Alavancagem em ativos voláteis pode te deixar com dívidas impagáveis se o ativo cair."}', 'hard'),
('consultor', '{"text": "Estudar sobre a empresa antes de comprar suas ações.", "type": "good", "explanation": "Essencial! Investimento requer análise. Comprar \"dicas\" sem entender é receita para o fracasso."}', 'hard');

-- Seed Data: Desafio de Termos (16 Terms)
INSERT INTO public.game_questions (game_type, content, difficulty) VALUES
('termo', '{"term": "Selic", "definition": "Taxa básica de juros da economia."}', 'easy'),
('termo', '{"term": "Liquidez", "definition": "Facilidade de transformar um ativo em dinheiro."}', 'easy'),
('termo', '{"term": "Dividendo", "definition": "Parte do lucro da empresa distribuída aos acionistas."}', 'easy'),
('termo', '{"term": "IPCA", "definition": "Índice oficial de inflação no Brasil."}', 'easy'),
('termo', '{"term": "CDB", "definition": "Empréstimo que você faz para o banco."}', 'easy'),
('termo', '{"term": "Volatilidade", "definition": "Variação do preço de um ativo ao longo do tempo."}', 'medium'),
('termo', '{"term": "Day Trade", "definition": "Compra e venda de ativos no mesmo dia."}', 'medium'),
('termo', '{"term": "FGC", "definition": "Garantia de até R$ 250 mil em caso de quebra do banco."}', 'medium'),
('termo', '{"term": "IOF", "definition": "Imposto sobre Operações Financeiras."}', 'medium'),
('termo', '{"term": "Câmbio", "definition": "Troca de uma moeda por outra (ex: Real por Dólar)."}', 'medium'),
('termo', '{"term": "Bear Market", "definition": "Mercado em tenência de baixa (pessimista)."}', 'hard'),
('termo', '{"term": "Bull Market", "definition": "Mercado em tendência de alta (otimista)."}', 'hard'),
('termo', '{"term": "PLR", "definition": "Participação nos Lucros e Resultados."}', 'hard'),
('termo', '{"term": "Royalty", "definition": "Pagamento pelo direito de uso de uma propriedade ou marca."}', 'hard'),
('termo', '{"term": "Benchmark", "definition": "Índice de referência para comparar rentabilidade."}', 'hard'),
('termo', '{"term": "Passivo", "definition": "Dívidas e obrigações financeiras."}', 'hard');

-- Seed Data: Empire Builder (8 Active, 8 Passive items)
INSERT INTO public.empire_items (name, type, base_cost, base_income, description) VALUES
-- Active (Click Multipliers)
('Vender Limonada', 'active', 10, 1, 'Trabalho honesto para começar.'),
('Passear com Cachorros', 'active', 50, 5, 'Exercício e dinheiro extra.'),
('Entregar Jornal', 'active', 150, 12, 'Acordar cedo rende frutos.'),
('Freelance Online', 'active', 500, 35, 'Usando suas habilidades digitais.'),
('Dar Aulas Particulares', 'active', 1500, 90, 'Compartilhando conhecimento.'),
('Consultoria Financeira', 'active', 5000, 250, 'Ensinando outros a enriquecer.'),
('Palestrar em Eventos', 'active', 20000, 800, 'Sua autoridade vale muito.'),
('Escrever Best-Seller', 'active', 100000, 3000, 'Royalties de um livro de sucesso.'),

-- Passive (Auto Income)
('Conta Poupança', 'passive', 100, 2, 'Rendimento baixo, mas é um começo.'),
('Tesouro Direto', 'passive', 500, 8, 'Empréstimo para o governo com segurança.'),
('Fundo Imobiliário (FII)', 'passive', 1500, 25, 'Aluguéis caindo na conta todo mês.'),
('Ações de Dividendos', 'passive', 5000, 100, 'Sócio de grandes empresas.'),
('Empréstimo P2P', 'passive', 15000, 250, 'Emprestar para outras pessoas via plataforma.'),
('Imóvel de Aluguel', 'passive', 50000, 700, 'Renda passiva clássica de tijolo.'),
('Franquia Automatizada', 'passive', 200000, 2500, 'Negócio escalável que roda sozinho.'),
('Shopping Center', 'passive', 1000000, 10000, 'O ápice do investidor imobiliário.');
